---
#
# Ansible managed
#
repository:
  description: Install and configure rabbitvcs on your system.
  homepage: https://robertdebock.nl/
  topics: rabbitvcs, development, ansible, molecule, tox, playbook
